<?php

function actuos_portal_menu() {
	$menu['settings'] = array (
			'title' => 'Settings',
			'page callback' => '_actuos_portal_menu_settings_callback',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);
	$menu['notifications'] = array	(
			'title' => 'Notifications',
			'page callback' => '_actuos_portal_menu_notifications_callback',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
	);
	$menu['news'] = array	(
			'title' => 'News',
			'page callback' => '_actuos_portal_menu_news_callback',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
	);
	$menu['portfolio-analysis'] = array	(
			'title' => 'Portfolio Analysis',
			'page callback' => '_actuos_portal_menu_portfolio_analysis_callback',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
	);
	$menu['performance'] = array	(
			'title' => 'Performance',
			'page callback' => '_actuos_portal_menu_performance_callback',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
	);
	$menu['sale-management'] = array	(
			'title' => 'Sale Management',
			'page callback' => '_actuos_portal_menu_sale_management_callback',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
	);
	$menu['post-sale'] = array	(
			'title' => 'Post Sale',
			'page callback' => '_actuos_portal_menu_post_sales_callback',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
	);
	return $menu;
}

function _actuos_portal_menu_settings_callback(){
	return array();
}
function _actuos_portal_menu_notifications_callback(){
	return array();
}
function _actuos_portal_menu_news_callback(){
	return array();
}
function _actuos_portal_menu_portfolio_analysis_callback(){
	return array();
}
function _actuos_portal_menu_performance_callback(){
	return array();
}
function _actuos_portal_menu_sale_management_callback(){
	return array();
}
function _actuos_portal_menu_post_sales_callback(){
	return array();
}